apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vue-simple-table
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: vue-simple-table
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: vue-simple-table
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/correlationid: tapdemoacr.azurecr.io/taptest:latest?sub_path=/
        apps.tanzu.vmware.com/debug: "true"
        apps.tanzu.vmware.com/live-update: "true"
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          developer-conventions/add-source-image-label
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.apps.tanzu.vmware.com/image-source-digest: tapdemoacr.azurecr.io/taptest:latest@sha256:101c5a64bf072f5f7feb798ff81a3d763554d002f07a40abef25fa6b22da39e9
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: vue-simple-table
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: vue-simple-table
    spec:
      containers:
      - image: tapdemoacr.azurecr.io/taptest/workloads/vue-simple-table-demo@sha256:c364c375a4703a1977c65edea3c05e025c2ccc06a7e5b3a33feb69496a3fa426
        name: workload
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
      serviceAccountName: default

